LoadModule auth_openidc_module /usr/lib/apache2/modules/mod_auth_openidc.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

ProxyPass / http://r_shiny_app:3838/
# ProxyPassReverse / http://r_shiny_app:3838/

include ./oidc.secret.conf

LogLevel debug auth_openidc:trace8
OIDCInfoHook iat access_token access_token_expires id_token id_token_hint userinfo refresh_token exp timeout remote_user session

# Auth endpoint configuration
<Location /entra>
    AuthType openid-connect
    OIDCCookie oidcstate
    OIDCCookiePath /
    Require valid-user
</Location>

<location />
    AuthType openid-connect
    OIDCCookie oidcstate
    OIDCCookiePath "/"
    Require claim groups:panel-lemanique-users_AppGrpU
</location>
